name: flask workflow

on:
  push:
      branches: 
          main
  pull_request:
      branches:
          main
  workflow_dispatch:


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: install python
          uses: actions/setup-python@v2
          with: 
            python-version: "3.10"

        - name: install dependencies
          run: |
            pip install flask
            pin install pytest

        - name: run pytest
          run: |
            pytest

        - name: login to docker hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: build docker image
          run: |
            docker build -t pammarty/myflask-app:latest . 
        
        - name: tag ang push to docker hub
          run: | 
            docker push pammarty/myflask-app:latest